# This configuration is not used for the final grading, you can change it if
# you know what you're doing.

stages:
  - build
  - grade

compile:
  stage: build
  image: lampepfl/moocs-dotty:2019-10-16
  except:
    - tags
  tags:
    - cs210
  script:
    - sbt packageSubmission
  artifacts:
    expire_in: 1 day
    paths:
      - submission.jar
