# This configuration is not used for the final grading, you can change it if
# you know what you're doing.

stages:
  - build
  - grade

compile:
  stage: build
  image: lampepfl/moocs-dotty:2019-09-17-2
  tags:
    - cs210
  script:
    - sbt packageSubmission
  artifacts:
    expire_in: 1 day
    paths:
      - submission.jar

grade:
  stage: grade
  tags:
    - cs210
  image:
    name: registry.gitlab.com/fnux/cs210-grading-images/progfun2-streams:20191030-43a7371aecb1bee74b8e4c3b0aba175f3ff4d0c6
    entrypoint: [""]
  allow_failure: true
  before_script:
    - mkdir -p /shared/submission/
    - cp submission.jar /shared/submission/submission.jar
  script:
    - cd /grader
    - /grader/grade | /grader/feedback-printer
