# This configuration is not used for the final grading, you can change it if
# you know what you're doing.

stages:
  - build
  - grade

compile:
  stage: build
  image: lampepfl/moocs-dotty:2019-10-16
  except:
    - tags
  tags:
    - cs210
  script:
    - sbt packageSubmission
  artifacts:
    expire_in: 1 day
    paths:
      - submission.jar

grade:
  stage: grade
  except:
    - tags
  tags:
    - cs210
  image:
    name: registry.gitlab.com/fnux/cs210-grading-images/progfun2-interpreter:20191205-066e2155681d802554c93c569bbf9871921a3ca1
    entrypoint: [""]
  allow_failure: true
  before_script:
    - mkdir -p /shared/submission/
    - cp submission.jar /shared/submission/submission.jar
  script:
    - cd /grader
    - /grader/grade | /grader/feedback-printer
